### ISSUE TITLE
Loading a SentencePiece protobuf

### ISSUE THREAD

**Issue by guillaume-be** [danieldk/sentencepiece#14]
Hello,

I'd like to load a sentence piece model file, and I thought about using your library for this purpose. I'd like not to actually have to install the C++ sentence piece library, and for now only load the model file into a Trie structure.

I see you used create a protobuf and compiled it into a Rust package. I tried using this compile protobuf withotu success so far:
```rust
use crate::sentencepiece::SentencePieceText;
use protobuf::parse_from_bytes;

let _contents = include_bytes!("path/to/toy.model");
let _ = parse_from_bytes::<SentencePieceText>(_contents).unwrap();
```

Could it be that I am trying to map the model to the wrong protobuf?
Thank you!

**Comment by danieldk** [comment]
For models you need this `ModelProto`:

https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto

I am not generating data types for those protobufs in Rust, since they are not needed when using the C++ API.

**Comment by guillaume-be** [comment]
Thank you!
