### ISSUE TITLE
Panic on encountering string with null byte

### ISSUE THREAD

**Issue by nikitakit** [danieldk/sentencepiece#43]
Rust strings are allowed to contain the null character (apparently 0 is a valid codepoint in UTF-8). Sentencepiece itself can handle this; for example in the python API you can call `model.encode("\0")` just fine. And the C++ API uses absl::string_view, which according to its documentation allows interior null characters.

However this rust wrapper casts rust str to CString, and then calls `unwrap` which panics:
https://github.com/danieldk/sentencepiece/blob/abdfb4c56c48b0eef53242123dc4451dfd2fe189/src/lib.rs#L192

I'm trying to use this library in a project involving large amounts of raw text, and part of why I find sentencepiece attractive is that it automatically takes care of and normalizes a large number of unicode artifacts. Would it be possible to adjust this wrapper to transparently pass strings to sentencepiece, even if they contain a null character?

**Comment by danieldk** [comment]
Good catch! Thanks for reporting this. #44 should fix this. Could you confirm that it works for you? Then I'll upload a new release to crates.io.

**Comment by nikitakit** [comment]
Thank you for the quick response! I've been running jobs with this bugfix for the past few days, and I can confirm that it fixes the issue and doesn't seem to break anything else in the process.

**Comment by danieldk** [comment]
Excellent! I have uploaded version 0.7.0 to crates.io.
