### ISSUE TITLE
Any plan to support detokenize

### ISSUE THREAD

**Issue by vegetarianz** [danieldk/sentencepiece#54]
Hi, wondering is there a plan to support decode api
https://github.com/google/sentencepiece/blob/master/doc/api.md#detokenize-text-postprocessing

**Comment by danieldk** [comment]
I didn't implement it, because I didn't have a need for it. But it would definitely nice to have support for the detokenization API as well!

I'll look into this.

**Comment by danieldk** [comment]
This is now supported in version 0.8.2: https://github.com/danieldk/sentencepiece/releases/tag/v0.8.2
