### ISSUE TITLE
Support for subword regularization (SampleEncode)

### ISSUE THREAD

**Issue by nikitakit** [danieldk/sentencepiece#56]
I would find it helpful to be able to use subword regularization with this library. In practice, that would mean wrapping `SampleEncodeAsSerializedProto` with a function very similar to `encode`, but accepting two additional arguments.

**Comment by danieldk** [comment]
Sounds good to me! I am currently quite busy with spaCy stuff, so I am not sure if I have time to look into this the coming days.

**Comment by danieldk** [comment]
Sorry that this took such a long time, but `main` now has a `SentencePieceProcessor::sample_encode`.
